# Learn how to set up Cypress in your CI environment
# https://on.cypress.io/ci
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  test:
    jobs:
      - cypress/run:
          post-install:
            - run: npx cypress info
          start: 'npm start'